### ISSUE TITLE
Error when path separator is '\' instead of '/'

### ISSUE THREAD

**Issue by bartoszluka** [janosh/pdf-compressor#9]
I'm using Windows with powershell and when I hit tab to autocomplete the filepath, I get '.\' prefix. This causes the following error:
```
$ pdf-compressor.exe .\simple.pdf
Traceback (most recent call last):
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\Scripts\pdf-compressor-script.py", line 33, in <module>
    sys.exit(load_entry_point('pdf-compressor==0.1.9', 'console_scripts', 'pdf-compressor')())
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\lib\site-packages\pdf_compressor\main.py", line 174, in main
    downloaded_file = task.download()
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\lib\site-packages\pdf_compressor\ilovepdf.py", line 273, in download
    with open(file_path, "wb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Bartek\\Downloads\\0-.\\simple-compress.pdf'
```
When I manually delete the backslash prefix or change the path sepator to '/' for example `pdf-compressor.exe Downloads/simple.pdf` everything works fine.
I'm using version 0.1.9
```
$ pdf-compressor.exe --version
PDF Compressor v0.1.9
```
Also attaching output with verbose flag enabled:
```
$ pdf-compressor.exe .\simple.pdf --verbose
PDFs to be compressed with iLovePDF: 1
Uploading file(s)...
File(s) uploaded and processed!
response = {'download_filename': '0-.\\simple-compress.pdf', 'filesize': 7861, 'output_filesize': 7861, 'output_filenumber': 1, 'output_extensions': '["pdf"]', 'timer': '0.043', 'status': 'TaskSuccess'}
Traceback (most recent call last):
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\Scripts\pdf-compressor-script.py", line 33, in <module>
    sys.exit(load_entry_point('pdf-compressor==0.1.9', 'console_scripts', 'pdf-compressor')())
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\lib\site-packages\pdf_compressor\main.py", line 174, in main
    downloaded_file = task.download()
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\lib\site-packages\pdf_compressor\ilovepdf.py", line 273, in download
    with open(file_path, "wb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Bartek\\Downloads\\0-.\\simple-compress.pdf'
```

**Comment by janosh** [comment]
Thanks for the bug report. I don't have access to a Windows machine myself so will have to setup GH action to run on Windows for testing.

To make it a bit easier, could you go into `File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\lib\site-packages\pdf_compressor\ilovepdf.py", line 273`, insert these 2 lines just before the line that throws the error and tell me what they print?

```py

        print(f"{save_to_dir=}")
        print(f"{self._process_response['download_filename']=}")
```

I'm guessing

```py
save_to_dir='C:\\Users\\Bartek\\Downloads'
self._process_response['download_filename']='0-.\\simple-compress.pdf'
```

**Comment by bartoszluka** [comment]
Exactly as you predicted
```
$ pdf-compressor.exe .\simple.pdf
save_to_dir='C:\\Users\\Bartek\\Downloads'
self._process_response['download_filename']='0-.\\simple-compress.pdf'
Traceback (most recent call last):
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\Scripts\pdf-compressor-script.py", line 33, in <module>
    sys.exit(load_entry_point('pdf-compressor==0.1.9', 'console_scripts', 'pdf-compressor')())
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\lib\site-packages\pdf_compressor\main.py", line 174, in main
    downloaded_file = task.download()
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\lib\site-packages\pdf_compressor\ilovepdf.py", line 275, in download
    with open(file_path, "wb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Bartek\\Downloads\\0-.\\simple-compress.pdf'
```

**Comment by janosh** [comment]
One more test to see if the leading 0 comes from the iLovePDF API (probably) or Powershell somehow.

Could you add

```py
    args = parser.parse_args(argv) # after this line 
+   print(f"{args.filenames=}")
```

to `"C:\Users\Bartek\AppData\Local\Programs\Python\Python310\lib\site-packages\pdf_compressor\main.py"`.

**Comment by bartoszluka** [comment]
```
$ pdf-compressor.exe .\simple.pdf
args.filenames=['.\\simple.pdf']
save_to_dir='C:\\Users\\Bartek\\Downloads'
self._process_response['download_filename']='0-.\\simple-compress.pdf'
Traceback (most recent call last):
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\Scripts\pdf-compressor-script.py", line 33, in <module>
    sys.exit(load_entry_point('pdf-compressor==0.1.9', 'console_scripts', 'pdf-compressor')())
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\lib\site-packages\pdf_compressor\main.py", line 175, in main
    downloaded_file = task.download()
  File "C:\Users\Bartek\AppData\Local\Programs\Python\Python310\lib\site-packages\pdf_compressor\ilovepdf.py", line 275, in download
    with open(file_path, "wb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Bartek\\Downloads\\0-.\\simple-compress.pdf'
```

**Comment by janosh** [comment]
Yeah, so that 0 is prepended to the filename by the API. I wonder why and what the best fix would be.

**Comment by bartoszluka** [comment]
I think Windows (or powershell) understands when filepaths are separated with '/'. Maybe the fix would be to '\' in the incoming file names with '/'?

**Comment by janosh** [comment]
@bartoszluka Happy to give it a shot. I pushed a [branch](https://github.com/janosh/pdf-compressor/tree/try-fix-win-fpath) to test this. You can install it with

```
pip uninstall pdf-compressor -y
pip install https://github.com/janosh/pdf-compressor/zipball/try-fix-win-fpath
```

**Comment by bartoszluka** [comment]
It works! Thank you very much!

**Comment by janosh** [comment]
Cool, will release this once I figure out why `setup-python` [fails on `windows-latest` in GHA](https://github.com/janosh/pdf-compressor/runs/5051115721?check_suite_focus=true#step:3:9).
